backend:
  name: github
  branch: master
  repo: mattortiz/mattortiz.com

media_folder: static/img
public_folder: /img

collections:
  - name: 'team'
    label: 'Team'
    folder: 'src/team'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Team Member', name: 'title', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'markdown' }
  - name: 'blog'
    label: 'Posts'
    folder: 'src/posts'
    create: true
    fields:
      - { name: 'slug', label: 'Path' }
      - { name: 'date', label: 'Date', widget: 'date' }
      - { name: 'title', label: 'Title' }
      - { name: 'body', label: 'Body', widget: 'markdown' }
